### ISSUE TITLE
add support for global CSS variables

### ISSUE THREAD

**Issue by robkorv** [robkorv/postcss-selector-prefix#58]
https://developer.mozilla.org/en-US/docs/Web/CSS/:root and https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

I think
```css
:root {
  --text-color: 16px;
}
```

Should be converted to:
```css
#pefix {
  --text-color: 16px;
}
```
